name: codequest_front
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.0-289.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.0.0 
  test: ^1.24.0
  window_manager: ^0.3.8
  http: ^1.6.0 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf